// Vendors the Google Fonts families used by the Issuerd web UIs into
// public/fonts/ so the consoles and the login page are fully self-hosted
// (no fonts.googleapis.com / fonts.gstatic.com requests at runtime — those
// fail in hermetic networks, e.g. the OIDC conformance stack).
//
// Usage:  node scripts/fetch-fonts.mjs   (requires internet access)
// Output: public/fonts/*.woff2 + public/fonts/fonts.css  (both committed)
//
// The generated fonts.css keeps Google's per-subset @font-face blocks
// (unicode-range + font-display: swap), only rewriting src to the local file.
// Variable weight ranges cover every weight the UI uses with one file per
// subset instead of one file per weight.

import { mkdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const FONTS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts')

const FAMILIES = [
  { query: 'Inter:wght@100..900', slug: 'inter' },
  { query: 'Space+Grotesk:wght@300..700', slug: 'space-grotesk' },
  { query: 'JetBrains+Mono:wght@100..800', slug: 'jetbrains-mono' },
]

// A desktop Chrome UA makes the css2 API answer woff2 (instead of ttf).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

const faceBlock =
  /\/\* ([a-z-]+) \*\/\s*@font-face \{\s*font-family: '([^']+)';\s*font-style: (\w+);\s*font-weight: ([^;]+);\s*font-display: (\w+);\s*src: url\((https:[^)]+)\) format\('woff2'\);\s*unicode-range: ([^;]+);\s*\}/g

let outCss = `/* Vendored Google Fonts — generated by scripts/fetch-fonts.mjs.\n`
outCss += `   Families: ${FAMILIES.map((f) => f.query.replaceAll('+', ' ')).join(', ')}.\n`
outCss += `   Source: https://fonts.googleapis.com/css2 (Open Font Licensed). Do not edit by hand. */\n\n`

await mkdir(FONTS_DIR, { recursive: true })

const written = new Set()
for (const { query, slug } of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${query}&display=swap`
  const res = await fetch(url, { headers: { 'user-agent': UA } })
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`)
  const css = await res.text()

  let match
  let count = 0
  while ((match = faceBlock.exec(css)) !== null) {
    const [, subset, family, style, weight, display, srcUrl, unicodeRange] = match
    const file = `${slug}-${subset}.woff2`
    const fontRes = await fetch(srcUrl)
    if (!fontRes.ok) throw new Error(`${srcUrl}: HTTP ${fontRes.status}`)
    await writeFile(join(FONTS_DIR, file), Buffer.from(await fontRes.arrayBuffer()))
    written.add(file)
    count += 1
    outCss += `/* ${family} — ${subset} */\n`
    outCss += `@font-face {\n`
    outCss += `  font-family: '${family}';\n`
    outCss += `  font-style: ${style};\n`
    outCss += `  font-weight: ${weight.trim()};\n`
    outCss += `  font-display: ${display};\n`
    outCss += `  src: url(./${file}) format('woff2');\n`
    outCss += `  unicode-range: ${unicodeRange.trim()};\n`
    outCss += `}\n\n`
  }
  if (count === 0) throw new Error(`${url}: no @font-face blocks parsed`)
  console.log(`${slug}: ${count} subset(s)`)
}

await writeFile(join(FONTS_DIR, 'fonts.css'), outCss)

// Drop woff2 files that are no longer referenced (family/weight set changed).
const { readdir } = await import('node:fs/promises')
for (const entry of await readdir(FONTS_DIR)) {
  if (entry.endsWith('.woff2') && !written.has(entry)) {
    await rm(join(FONTS_DIR, entry))
    console.log(`removed stale ${entry}`)
  }
}

console.log(`fonts.css + ${written.size} woff2 file(s) written to public/fonts/`)
