options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    allow-query { any; };
    recursion yes;
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    dnssec-validation no;
};

zone "test.local" {
    type master;
    file "/etc/bind/zones/db.test.local";
};
