// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Dmitry Andreev. <da@issuerd.org>
//
// OpenAPI specification assembly for the Admin REST API.

use utoipa::OpenApi;

struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                utoipa::openapi::security::SecurityScheme::Http(
                    utoipa::openapi::security::HttpBuilder::new()
                        .scheme(utoipa::openapi::security::HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
            components.add_security_scheme(
                "oidc_auth",
                utoipa::openapi::security::SecurityScheme::OAuth2(
                    utoipa::openapi::security::OAuth2::new([
                        utoipa::openapi::security::Flow::AuthorizationCode(
                            utoipa::openapi::security::AuthorizationCode::with_refresh_url(
                                "/realms/master/protocol/openid-connect/auth",
                                "/realms/master/protocol/openid-connect/token",
                                utoipa::openapi::security::Scopes::from_iter([
                                    ("openid", "OpenID Connect"),
                                    ("profile", "Profile information"),
                                ]),
                                "/realms/master/protocol/openid-connect/token",
                            ),
                        ),
                    ]),
                ),
            );
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Issuerd Admin API",
        description = "RESTful Admin API for managing Issuerd IAM realms, users, clients, roles, groups, sessions, identity providers, and authentication flows. All endpoints require a valid Bearer token with appropriate realm-management roles.",
        version = "0.1.0",
        contact(name = "Issuerd", url = "https://github.com/issuerd/issuerd")
    ),
    paths(
        crate::realms::list_realms,
        crate::realms::count_realms,
        crate::realms::create_realm,
        crate::realms::get_realm,
        crate::realms::update_realm,
        crate::realms::delete_realm,
        crate::users::list_users,
        crate::users::count_users,
        crate::users::create_user,
        crate::users::get_user,
        crate::users::update_user,
        crate::users::delete_user,
        crate::users::get_user_sessions,
        crate::users::reset_password,
        crate::credentials::list_user_credentials,
        crate::credentials::update_credential_label,
        crate::credentials::delete_credential,
        crate::credentials::move_credential_after,
        crate::user_actions::execute_actions_email,
        crate::user_actions::impersonate_user,
        crate::users::get_user_role_mappings,
        crate::users::get_user_realm_roles,
        crate::users::add_user_realm_roles,
        crate::users::remove_user_realm_roles,
        crate::users::get_available_user_realm_roles,
        crate::users::get_effective_user_realm_roles,
        crate::users::get_user_client_roles,
        crate::users::add_user_client_roles,
        crate::users::remove_user_client_roles,
        crate::users::get_available_user_client_roles,
        crate::users::get_effective_user_client_roles,
        crate::users::get_user_groups,
        crate::users::add_user_group,
        crate::users::remove_user_group,
        crate::attack_detection::list_locked_users,
        crate::attack_detection::get_user_brute_force_status,
        crate::attack_detection::clear_user_brute_force_state,
        crate::realms::test_smtp_connection,
        crate::import_export::partial_import,
        crate::import_export::export_realm,
        crate::import_export::push_revocation,
        crate::clients::list_clients,
        crate::clients::count_clients,
        crate::clients::create_client,
        crate::clients::get_client,
        crate::clients::update_client,
        crate::clients::delete_client,
        crate::clients::get_client_secret,
        crate::clients::rotate_client_secret,
        crate::clients::get_service_account_user,
        crate::client_installation::get_installation_provider,
        crate::initial_access::create_initial_access_token,
        crate::initial_access::list_initial_access_tokens,
        crate::initial_access::delete_initial_access_token,
        crate::client_roles::list_client_roles,
        crate::client_roles::create_client_role,
        crate::client_roles::get_client_role,
        crate::client_roles::update_client_role,
        crate::client_roles::delete_client_role,
        crate::composites::get_client_role_composites,
        crate::composites::add_client_role_composites,
        crate::composites::remove_client_role_composites,
        crate::composites::get_client_role_composites_realm,
        crate::composites::get_client_role_composites_clients,
        crate::client_scopes::list_client_scopes,
        crate::client_scopes::create_client_scope,
        crate::client_scopes::get_client_scope,
        crate::client_scopes::update_client_scope,
        crate::client_scopes::delete_client_scope,
        crate::client_scopes::list_scope_mappers,
        crate::client_scopes::create_scope_mapper,
        crate::client_scopes::get_scope_mapper,
        crate::client_scopes::update_scope_mapper,
        crate::client_scopes::delete_scope_mapper,
        crate::client_scopes::list_client_mappers,
        crate::client_scopes::create_client_mapper,
        crate::client_scopes::get_client_mapper,
        crate::client_scopes::update_client_mapper,
        crate::client_scopes::delete_client_mapper,
        crate::client_scopes::get_default_client_scopes,
        crate::client_scopes::assign_default_client_scope,
        crate::client_scopes::unassign_default_client_scope,
        crate::client_scopes::get_optional_client_scopes,
        crate::client_scopes::assign_optional_client_scope,
        crate::client_scopes::unassign_optional_client_scope,
        crate::client_scopes::list_default_default_client_scopes,
        crate::client_scopes::add_default_default_client_scope,
        crate::client_scopes::remove_default_default_client_scope,
        crate::client_scopes::list_default_optional_client_scopes,
        crate::client_scopes::add_default_optional_client_scope,
        crate::client_scopes::remove_default_optional_client_scope,
        crate::scope_mappings::get_client_scope_mappings,
        crate::scope_mappings::get_scope_mapping_realm_roles,
        crate::scope_mappings::add_scope_mapping_realm_roles,
        crate::scope_mappings::remove_scope_mapping_realm_roles,
        crate::scope_mappings::get_available_scope_mapping_realm_roles,
        crate::scope_mappings::get_effective_scope_mapping_realm_roles,
        crate::scope_mappings::get_scope_mapping_client_roles,
        crate::scope_mappings::add_scope_mapping_client_roles,
        crate::scope_mappings::remove_scope_mapping_client_roles,
        crate::scope_mappings::get_available_scope_mapping_client_roles,
        crate::scope_mappings::get_effective_scope_mapping_client_roles,
        crate::roles::list_realm_roles,
        crate::roles::count_realm_roles,
        crate::roles::create_realm_role,
        crate::roles::get_realm_role,
        crate::roles::update_realm_role,
        crate::roles::delete_realm_role,
        crate::composites::get_realm_role_composites,
        crate::composites::add_realm_role_composites,
        crate::composites::remove_realm_role_composites,
        crate::composites::get_realm_role_composites_realm,
        crate::composites::get_realm_role_composites_clients,
        crate::groups::list_groups,
        crate::groups::count_groups,
        crate::groups::create_group,
        crate::groups::create_child_group,
        crate::groups::get_group,
        crate::groups::update_group,
        crate::groups::delete_group,
        crate::groups::get_group_members,
        crate::groups::get_group_role_mappings,
        crate::groups::get_group_realm_roles,
        crate::groups::add_group_realm_roles,
        crate::groups::remove_group_realm_roles,
        crate::groups::get_available_group_realm_roles,
        crate::groups::get_effective_group_realm_roles,
        crate::groups::get_group_client_roles,
        crate::groups::add_group_client_roles,
        crate::groups::remove_group_client_roles,
        crate::groups::get_available_group_client_roles,
        crate::groups::get_effective_group_client_roles,
        crate::sessions::list_sessions,
        crate::sessions::count_sessions,
        crate::sessions::delete_session,
        crate::events::query_events,
        crate::events::count_events,
        crate::events::query_admin_events,
        crate::events::count_admin_events,
        crate::events::get_events_config,
        crate::events::update_events_config,
        crate::events::clear_events,
        crate::events::clear_admin_events,
        crate::idp::list_idps,
        crate::idp::create_idp,
        crate::idp::get_idp,
        crate::idp::update_idp,
        crate::idp::delete_idp,
        crate::idp::list_idp_mappers,
        crate::idp::create_idp_mapper,
        crate::idp::update_idp_mapper,
        crate::idp::delete_idp_mapper,
        crate::idp::test_idp_connection,
        crate::keys::get_keys,
        crate::keys::rotate_keys,
        crate::keys::disable_key,
        crate::flows::list_flows,
        crate::flows::create_flow,
        crate::flows::get_flow,
        crate::flows::update_flow,
        crate::flows::delete_flow,
        crate::flows::copy_flow,
        crate::flows::add_execution,
        crate::flows::add_flow_execution,
        crate::flows::update_execution,
        crate::flows::get_execution,
        crate::flows::delete_execution,
        crate::flows::get_execution_config,
        crate::flows::create_execution_config,
        crate::flows::update_execution_config,
        crate::flows::delete_execution_config,
        crate::federation::sync_users,
        crate::enums::get_serverinfo,
        crate::enums::list_protocols,
        crate::enums::list_ssl_required,
        crate::enums::list_event_types,
        crate::enums::list_event_listeners,
        crate::enums::list_credential_types,
        crate::enums::list_algorithms,
        crate::enums::list_grant_types,
        crate::enums::list_response_types,
        crate::enums::list_response_modes,
        crate::enums::list_requirements,
        crate::enums::list_authenticators,
        crate::enums::list_provider_ids,
        crate::enums::list_client_authenticator_types,
        crate::enums::list_operation_types,
        crate::enums::list_prompts,
        crate::enums::list_resource_types,
        crate::enums::list_hash_algorithms,
        crate::enums::list_auth_methods,
        crate::enums::list_pkce_code_challenge_methods,
        crate::enums::list_jwk_use,
        crate::enums::list_jwk_key_types,
        crate::enums::list_ldap_vendors,
        crate::enums::list_ldap_search_scopes,
        crate::enums::list_edit_modes,
        crate::enums::list_required_actions,
        crate::enums::list_otp_algorithms,
        crate::enums::list_broker_sync_modes,
        crate::enums::list_broker_client_auth_methods,
        crate::enums::list_idp_mapper_types,
        crate::enums::list_mapper_types,
        crate::enums::list_locales,
        crate::enums::list_themes,
        crate::enums::list_identity_provider_presets,
        crate::enums::list_subject_types,
        crate::enums::list_client_installations,
    ),
    components(schemas(
        crate::dto::RealmRepresentation,
        crate::dto::UserRepresentation,
        crate::dto::CredentialRepresentation,
        crate::dto::UpdateCredentialLabelRequest,
        crate::dto::ImpersonationResponse,
        crate::dto::ClientRepresentation,
        crate::dto::ClientSecret,
        crate::dto::InitialAccessTokenCreateRequest,
        crate::dto::InitialAccessTokenRepresentation,
        crate::dto::RoleRepresentation,
        crate::dto::MappingsRepresentation,
        crate::dto::ClientMappingsRepresentation,
        crate::dto::ClientScopeRepresentation,
        crate::dto::ProtocolMapperRepresentation,
        issuerd_core::MapperType,
        crate::dto::GroupRepresentation,
        issuerd_core::GroupId,
        crate::dto::UserSessionRepresentation,
        crate::dto::EventRepresentation,
        crate::dto::AdminEventRepresentation,
        crate::dto::RealmEventsConfigRepresentation,
        crate::dto::IdentityProviderRepresentation,
        issuerd_core::IdpMapper,
        issuerd_core::IdpMapperType,
        issuerd_core::IdpPreset,
        crate::idp::IdpTestConnectionResponse,
        crate::dto::KeyMetadataRepresentation,
        crate::dto::KeysMetadataRepresentation,
        crate::dto::FlowRepresentation,
        crate::dto::FlowStageRepresentation,
        crate::dto::AuthenticatorConfigRepresentation,
        crate::dto::CopyFlowRequest,
        crate::dto::AddExecutionRequest,
        crate::dto::AddFlowExecutionRequest,
        crate::dto::UpdateExecutionRequest,
        crate::dto::AuthenticatorConfigRequest,
        crate::dto::EnumValueRepresentation,
        crate::dto::ServerInfoRepresentation,
        crate::dto::CountRepresentation,
        crate::dto::SyncResultRepresentation,
        crate::dto::TestSmtpConnectionRequest,
        crate::dto::BruteForceLockoutRepresentation,
        crate::dto::BruteForceUserStatusRepresentation,
        crate::dto::IfResourceExists,
        crate::dto::PartialImportRepresentation,
        crate::dto::PartialImportRolesRepresentation,
        crate::dto::ImportAction,
        crate::dto::PartialImportResultEntry,
        crate::dto::PartialImportResultRepresentation,
        crate::dto::RealmExportRepresentation,
        crate::dto::ExportRolesRepresentation,
        crate::error::AdminApiErrorResponse,
    )),
    modifiers(&SecurityAddon),
    security(("bearer_auth" = []), ("oidc_auth" = [])),
    tags(
        (name = "Realms", description = "Realm lifecycle management"),
        (name = "Users", description = "User accounts, credentials, role-mappings, and group memberships"),
        (name = "Clients", description = "OIDC/OAuth2 client applications and secrets"),
        (name = "Client Roles", description = "Role definitions owned by a client"),
        (name = "Client Scopes", description = "Client scopes, protocol mappers, and realm default scope tables"),
        (name = "Scope Mappings", description = "Role allow-lists applied to client tokens"),
        (name = "Roles", description = "Realm and client role definitions"),
        (name = "Groups", description = "User groups and hierarchical memberships"),
        (name = "Sessions", description = "Active user session inspection and revocation"),
        (name = "Events", description = "Audit event querying, configuration, and clearing"),
        (name = "Identity Providers", description = "External IdP federation configuration"),
        (name = "User Federation", description = "LDAP and Kerberos user federation sync"),
        (name = "Keys", description = "Cryptographic key metadata, rotation, and status"),
        (name = "Authentication Flows", description = "Authentication and authorization flow definitions"),
        (name = "Server Info", description = "Server metadata and supported configuration values"),
        (name = "Enums", description = "Constant lists for dropdowns and comboboxes"),
        (name = "Attack Detection", description = "Brute-force lockout inspection and clearing"),
    )
)]
pub struct AdminApiDoc;

#[cfg(test)]
mod tests {
    use super::*;
    use utoipa::OpenApi;

    #[test]
    fn openapi_does_not_overflow() {
        let _ = AdminApiDoc::openapi();
    }
}
