-- Shop demo schema for the McpServer security demo.
--
-- Runs once on a fresh PostgreSQL volume (docker-entrypoint-initdb.d) as the
-- bootstrap superuser `issuerd`. Key properties:
--   * The orders table is owned by the superuser. PostgreSQL RLS does NOT
--     apply to the table owner, which is exactly why the app connects as the
--     non-owner role `mcp_user` — the policy below then filters every query.
--   * The policy uses current_setting('app.user_sub', true) (missing-ok), so
--     a connection without the RLS context yields zero rows instead of an
--     error. The app sets it per transaction via set_config(..., true).
--   * No rows are seeded here: user subs are random UUIDs generated by the
--     IdP at provisioning time. Seeding happens in the one-shot `setup`
--     compose service (setup/setup.py) once real user UUIDs exist.

CREATE ROLE mcp_user LOGIN PASSWORD 'RJUT-vefyAjQ5sL9Ia8sjwCs';

CREATE DATABASE shop;

\connect shop

CREATE TABLE orders (
  id integer PRIMARY KEY,
  owner_sub uuid NOT NULL,
  item text NOT NULL,
  amount numeric(10,2) NOT NULL,
  status text NOT NULL DEFAULT 'paid'
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY orders_owner ON orders
  USING (owner_sub = current_setting('app.user_sub', true)::uuid);

GRANT CONNECT ON DATABASE shop TO mcp_user;
GRANT USAGE ON SCHEMA public TO mcp_user;
GRANT SELECT, UPDATE ON orders TO mcp_user;
